receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 200
    sampling_thereafter: 200

processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
